apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: portfolio
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vllm-service
  namespace: portfolio
subsets:
  - addresses:
      - ip: "192.168.0.199"
    ports:
      - port: 8000
